FROM dong77/ubuntu_vagrant

# ensure we have the en_US.UTF-8 locale available
RUN apt-get update -y 
RUN apt-get install -y \
    software-properties-common \
    python-software-properties     
          
RUN add-apt-repository -y ppa:webupd8team/java 
RUN add-apt-repository -y ppa:git-core/ppa      
RUN apt-get update -y  

RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections     
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections       
RUN apt-get install -y \
    oracle-java8-installer \
    curl \
    scala \
    golang \
    git
