FROM ubuntu:16.04

RUN \
  set -x && \
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y --no-install-recommends openssh-server sudo && \

  # "vagrant" User
  useradd -s /bin/bash vagrant && \
  echo vagrant:vagrant | chpasswd -m && \
  install -m 755 -o vagrant -g vagrant -d /home/vagrant && \
  install -m 700 -o vagrant -g vagrant -d /home/vagrant/.ssh && \
  echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key' > /home/vagrant/.ssh/authorized_keys \
  chmod 600 /home/vagrant/.ssh/authorized_keys && \
  chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys && \

  # Root Password: "vagrant"
  echo root:vagrant | chpasswd -m && \

  # Password-less Sudo
  echo 'vagrant ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/vagrant && \
  chmod 0440 /etc/sudoers.d/vagrant && \

  # SSH Tweaks
  echo 'UseDNS no' >> /etc/ssh/sshd_config && \

  # for Vagrant OS detection
  #
  # https://github.com/mitchellh/vagrant/blob/v1.8.4/plugins/guests/ubuntu/guest.rb
  apt-get install -y --no-install-recommends lsb-release && \

  # Other Docker image fixes
  mkdir -p /var/run/sshd && \
  rm /usr/sbin/policy-rc.d && \

  # "vagrant-cachier" friendly
  rm /etc/apt/apt.conf.d/docker-clean && \

  # Cleanup
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# ensure we have the en_US.UTF-8 locale available
RUN apt-get update -y 
RUN apt-get install -y \
    software-properties-common \
    python-software-properties     
          
RUN add-apt-repository -y ppa:webupd8team/java 
RUN add-apt-repository -y ppa:git-core/ppa      
RUN apt-get update -y  

RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections     
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections       
RUN apt-get install -y \
    oracle-java8-installer \
    curl \
    scala \
    golang \
    git \
    gradle \
    lsb-release

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]