FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

# ensure we have the en_US.UTF-8 locale available
RUN locale-gen en_US.UTF-8


RUN apt-get update -y 
RUN apt-get install -y \
    software-properties-common \
    python-software-properties     
          
          
RUN add-apt-repository -y ppa:webupd8team/java 
RUN add-apt-repository -y ppa:git-core/ppa      
RUN apt-get update -y  

RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections     
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections       
RUN apt-get install -y \
    oracle-java8-installer 
    curl \
    lsb-release \
    openssh-server \
    sudo \
    scala \
    golang \
    rsync \
    git


# setup the vagrant user
RUN if ! getent passwd vagrant; then useradd -d /home/vagrant -m -s /bin/bash vagrant; fi \
    && echo vagrant:vagrant | chpasswd \
    && echo 'vagrant ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && mkdir -p /etc/sudoers.d \
    && echo 'vagrant ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/vagrant \
    && chmod 0440 /etc/sudoers.d/vagrant

# add the vagrant insecure public key
RUN mkdir -p /home/vagrant/.ssh \
    && chmod 0700 /home/vagrant/.ssh \
    && wget --no-check-certificate \
      https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub \
      -O /home/vagrant/.ssh/authorized_keys \
    && chmod 0600 /home/vagrant/.ssh/authorized_keys \
    && chown -R vagrant /home/vagrant/.ssh

# don't clean packages, we might be using vagrant-cachier
RUN rm /etc/apt/apt.conf.d/docker-clean

# run sshd in the foreground
CMD /usr/sbin/sshd -D \
    -o UseDNS=no\
    -o UsePAM=no\
    -o PasswordAuthentication=yes\
    -o UsePrivilegeSeparation=no\
    -o PidFile=/tmp/sshd.pid

